region                                = "eu-west-1"
cluster_name                          = "namiview-prod"
argocd_target_revision                = "main"
argocd_infrastructure_target_revision = "88-bootstrap-dev-environment-in-eks-cluster-shape-2"
argocd_dev_target_revision            = "88-bootstrap-dev-environment-in-eks-cluster-shape-2"
