region                                = "eu-west-1"
kubeconfig_path                       = "/Users/dar/.kube/config"
kubeconfig_context                    = "homelab"
argocd_target_revision                = "103-hybrid-homelab-aws-move-compute-from-eks-to-homelab"
argocd_dev_target_revision            = "103-hybrid-homelab-aws-move-compute-from-eks-to-homelab"
argocd_infrastructure_target_revision = "103-hybrid-homelab-aws-move-compute-from-eks-to-homelab"
